@startuml

!define COMMAND #Orange
!define STATE #LightBlue
!define EVENT #LightGreen

rectangle command {
    rectangle AddItemWithStock COMMAND
    rectangle AddItemWithoutStock COMMAND
    rectangle IncreaseStock COMMAND
    rectangle DecreaseStock COMMAND
    rectangle RemoveItem COMMAND
}

rectangle event {
    rectangle ItemAddedWithStock EVENT
    rectangle ItemAddedWithoutStock EVENT
    rectangle StockIncreased EVENT
    rectangle StockDecreased EVENT
    rectangle ItemRemoved EVENT
    rectangle PutOutOfStock EVENT
}

rectangle "initial state" {
    rectangle NoItem as NoItemIS1 STATE
    rectangle InStock as InStockIS1 STATE
    rectangle OutOfStock as OutOfStockIS1 STATE
}

rectangle "new state" {
    rectangle Removed as RemovedNS1 STATE
    rectangle InStock as InStockNS1 STATE
    rectangle InStock as InStockNS2 STATE
    rectangle InStock as InStockNS3 STATE
    rectangle OutOfStock as OutOfStockNS1 STATE
    rectangle OutOfStock as OutOfStockNS2 STATE
}

'AddItemWithStock
NoItemIS1 .down--> AddItemWithStock
AddItemWithStock -down--> ItemAddedWithStock
ItemAddedWithStock -down--> InStockNS1

'AddItemWithoutStock
NoItemIS1 .down-> AddItemWithoutStock
AddItemWithoutStock -down-> ItemAddedWithoutStock
ItemAddedWithoutStock -down-> OutOfStockNS1

'IncreaseStock
InStockIS1 .down-> IncreaseStock
OutOfStockIS1 .down-> IncreaseStock
IncreaseStock -down-> StockIncreased
StockIncreased -down-> InStockNS2

'DecreaseStock
InStockIS1 .down-> DecreaseStock
DecreaseStock -down-> StockDecreased
DecreaseStock -down-> PutOutOfStock
StockDecreased -down-> InStockNS3
PutOutOfStock -down-> OutOfStockNS2

'RemoveItem
InStockIS1 .down-> RemoveItem
OutOfStockIS1 .down-> RemoveItem
RemoveItem -down-> ItemRemoved
ItemRemoved -down-> RemovedNS1

@enduml