@startuml
state NoLightbulb
state Acquired {
    state NotConnected
    state Connected {
        state Off
        state On
        state Flickering
    }

    state NonFunctioning
}

state Disposed






[*] -down-> NoLightbulb
NoLightbulb -down-> NonFunctioning : acquired in broken state
NoLightbulb -down-> NotConnected : acquired

NotConnected -down-> Off : plugged in and\nno stream detected
NotConnected -down-> On : plugged in and\nstream detected
NotConnected -left-> NonFunctioning : broken
Connected -up-> NonFunctioning : broken
Connected -down-> NotConnected : disconnected

On -down--> Off : turned off
On -left-> Flickering : flickering initiated

Off -down-> On : turned on

Flickering -down-> Off : turned off
Flickering -right-> On : flickering terminated

Acquired -right----> Disposed : disposed

@enduml
