@startuml

state NoMatch
state New
state InProgress
state Suspended
state Cancelled
state Terminated

[*] -down-> NoMatch
NoMatch -down-> New : register
New -down-> InProgress : set in progress
New -down-> Cancelled : cancel
InProgress -down-> Suspended : suspend
InProgress -down-> Terminated : terminate
InProgress -down-> New : revert to new
Suspended -down-> InProgress : set back to in progress
Terminated -down-> InProgress : set back to in progress
Cancelled -down-> New : revert to new


@enduml